
export const carddata = [
    {
        id:1,
        imgsrc :'/Images/Airdopes_141.jpg',
        alt:"wire_less_earburds.jpg",
        title :  "Airdopes 141",
        imgsrc1 :'/Images/Star_img.jpg',
        alt1:"Rating",
        rate : "4.8",
        regprc : "4200",
        saleprc :"1200",
        per : "72",
    },
    {
        id:2,
        imgsrc :'/Images/Airpodes_131.jpg',
        alt:"wire_less_earburds.jpg",
        title :  "Airpodes 131",
        imgsrc1 :'/Images/Star_img.jpg',
        alt1:"Rating",
        rate:"4.8",
        regprc : "2990",
        saleprc :"999",
        per : "67",  
        
    },
    {
        id:3,
        imgsrc :'/Images/Airpodes_131_Pro.jpg',
        alt:"wire_less_earburds.jpg",
        title :  "Airdopes 131pro",
        imgsrc1 :'/Images/Star_img.jpg',
        alt1:"Rating",
        rate:"4.9",
        regprc : "2990",
        saleprc :"1299",
        per : "57",  
    },
    {
        id:4,
        imgsrc :'/Images/Airpodes_Atom_81.jpg',
        alt:"wire_less_earburds.jpg",
        title :  "Airdopes 81",
        imgsrc1 :'/Images/Star_img.jpg',
        alt1:"Rating", 
        rate:"5.0",
        regprc : "3490",
        saleprc :"999",
        per : "71",  
    },
    {
        id:5,
        imgsrc :'/Images/Airpodes_161.jpg',
        alt:"wire_less_earburds.jpg",
        title :  "Airdopes 161",
        imgsrc1 :'/Images/Star_img.jpg',
        alt1:"Rating", 
        rate:"4.9",
        regprc : "2490",
        saleprc :"1,099",
        per : "56",  
    },
    {
        id:6,
        imgsrc :'/Images/Airpodes_148.jpg',
        alt:"wire_less_earburds.jpg",
        title :  "Airpodes 148",
        imgsrc1 :'/Images/Star_img.jpg',
        alt1:"Rating", 
        rate:"5.0",
        regprc : "4490",
        saleprc :"1,499",
        per : "67",  
    },
    {
        id:7,
        imgsrc :'/Images/Airdopes_191G.jpg',
       
        title :  "Airdopes 191G",
      
       
        rate:"4.9",
        regprc : "3490",
        saleprc :" 1,799",
        modal:"Rockerz_Wireless",
        per : "48",  
    },
    {
    id:8,
    imgsrc :'/Images/Airpodes_192.jpg',
    alt:"wire_less_earburds.jpg",
    title :  "Airdopes 192",
    imgsrc1 :'/Images/Star_img.jpg',
    alt1:"Rating", 
    rate:"5.0",
    regprc : "3490",
    saleprc :"1999",
    per : "43",  
},
]
